### ISSUE TITLE
uwp二进制检查不兼容

### ISSUE THREAD

**Issue by FgoDt** [amamiya/SYEngine#12]
uwp在提交应用的时候检测出问题 MFGetService 这个函数不支持，也是最近才有的

    API MFGetService in mf.dll is not supported for this application type. SYEngine.dll calls this API.

**Comment by amamiya** [comment]
已修，但是没打包vsix，如果你是源码级整合，已经可以用了。

**Comment by FgoDt** [comment]
非常感谢，微软二进制检查越来越烦了
