### ISSUE TITLE
Is there a plan to upgrade from MediaElement to MediaPlayerElement?

### ISSUE THREAD

**Issue by TaoziDB** [amamiya/SYEngine#16]
As title, or a way to work with MediaPlayerElement, thanks.

**Comment by vbfool** [comment]
There is the same way to use them.

**Comment by TaoziDB** [comment]
MediaPlayerElement is much easier to support background media play, especially background audio on xbox

**Comment by vbfool** [comment]
MediaPlayerElement 和MediaElement的用法区别很大么？
直接支持的还“升级”什么啊。
