### ISSUE TITLE
爱奇艺源播放问题

### ISSUE THREAD

**Issue by wcavell** [amamiya/SYEngine#2]
爱奇艺的视频源是个f4v，f4v本来是MP4的变种，系统能直接播放，然而爱奇艺的f4v却是一个实实在在的flv结构。MediaExtensionManager里注册一个就可以了吧？

**Comment by amamiya** [comment]
不用注册也可以，因为播放网络流并不是根据扩展名决定的，既然是flv，服务器肯定会返回正确的mimetype，其实它不返回正确的也行。
你直接把地址输入进去播放试试就知道了。
主要我没有测试过爱奇艺，也不懂情况咋样。

**Comment by wcavell** [comment]
播放失败
Content-Type: application/octet-stream
并不能识别为flv

**Comment by amamiya** [comment]
给我个爱奇艺的视频地址。

**Comment by wcavell** [comment]
http://116.31.98.19/videos/v0/20151217/53/b1/ade7fc44ed3acdcc4df2a576d32fc51b.f4v?key=0a2c077ef1b28107d9bea5a7627beaa27&src=iqiyi.com&ran=1718&qyid=24449e7b57ec56fb357933467c8e2a4a&qypid=430907500_11&ran=1718&uuid=b7202d53-5672aacd-35&range=0-6815743&qypid=430907500_01010011010000000000_4&ran=1743

**Comment by wcavell** [comment]
如果地址的时效性问题
可以请求http://pdata.video.qiyi.com/5e1a9738aa4d15c87fddaaa232a3e416/videos/v0/20151107/34/85/76510737af67d64574b3aaa25753813d.f4v 获得一个json，里面有个新的视频地址。

**Comment by amamiya** [comment]
好，了解了。
其实第四个按钮Test for MultipartStreamMatroska (Network)可以播，但是seek有问题。。。奇怪。。
系统的Play Network我现在修修。

**Comment by amamiya** [comment]
Play Network可以了。
（f4v是什么鬼。。。这货貌似也没正常的MimeType么。

**Comment by amamiya** [comment]
后面在Initialize的参数里面给个list，自己需要add的private的mimetype自己用一个list去初始化好了。

**Comment by amamiya** [comment]
我跟朋友研究了下爱奇异的视频播放和无缝切片过渡。。
发现目前播放爱奇异这种网站还是挺困难的，我感觉并不想支持爱奇异这种源。
没有必要，让他们自己处理吧。

1、每个切片的FLV，下一个切片的时间戳，竟然是从上一个切片的duration开始打，比如上一个切片360秒结束，下一个切片第一个帧竟然是360秒。。我日。。
2、关键帧索引貌似有问题，seek会出问题。。爱奇异是把关键帧索引分开了的，用一个xml来存储关键帧索引，这实在太猎奇了。
3、从cdn获取到真正的f4v地址，持续时间太短了，测试了一下，获取到一个f4v地址，6分钟的一个切片，URL可用时间竟然只有不到10分钟，假设用户播放的时候暂停超过5分钟，URL就失效了，然而播放器会直接重头开始尝试连接，但是URL已经失效了，重新连接也没用啊。
而且我目前的切片播放逻辑是一开始就需要把所有URL都解析出来，然后保证这些URL在视频播放期间一直有效的。
除非我优化做像ijkplayer那样的动态要求主程序提供下一个分段的URL，但是我感觉没必要目前。

怪不得爱奇异不提供mp4的源，因为根本没必要啊，flv就flv，反正都是要使用自己的一套逻辑的播放器来播的。。

**Comment by wcavell** [comment]
嗯，既然这样，不支持爱奇艺也没啥，毕竟我对爱奇艺的需求并不高。 而且爱奇艺还是有hls方案的，只是质量差而已。

**Comment by amamiya** [comment]
最近有在做针对271这样的切片视频源的优化。
加了2个事件，事件会在：
1、快要切换下一个切片的时候（opType=NEXT，触发的时机为FetchNextPartThresholdSeconds指定的时长，默认30秒）
2、用户突然跳播到某一个切片的时候（opType=SEEK）
3、暂停了很久，突然又恢复播放的时候（opType=GAP）

在这些情况下，会通知到C#层的APP监听的event回调，可以在这里重新连接网络更新URL，并且可以更新连接时候的http的headers，然后会使用更新后的地址来播放。
这个完全是针对271这种脑残逻辑的源设计的，理论上，是可以完全应付271的了。

使用方法大概就是（类似于ijkplayer的逻辑）：
0、在某个PlayerPage里面监听Core下面的2个事件，271的话需要用Detail的事件，Detail的事件比只更新url的事件优先级高。
1、解析出这个视频源有几个url，Playlist在Append的时候，除了第一个分段的URL添加真的以外，其他分段的URL都可以添加一个假的，并且Append的时候，把每个切片的时长都添加上。
然后把ExplicitTotalDurationSeconds设置为总的时长，这个就是MediaElement会显示的时长，然后把DetectDurationForParts=false，让Open的时候不要去打开每个切片获取时长。（因为除了第一个URL其他都是假的）
2、设置UniqueId字符串，不设置这个不会触发更新URL的callback，callback触发的时候，这个被当作参数传过去。
3、在触发callback的时候，连接网络更新URL，callback卡住的时间不要超过5秒钟（默认），要改这个时间，可以使用Core.ChangeNetworkPreloadTime。
