### ISSUE TITLE
Existing app

### ISSUE THREAD

**Issue by GAMELASTER** [amamiya/SYEngine#5]
Hello,
(i know u are not good english, so fast)
Is exists a working app for download?
(It is good decoding a anime MKV? :-D )

Thanks

**Comment by silverdragon727** [comment]
Well, there's a rough demo app project that you could build by yourself. (https://github.com/amamiya/SYEngine/tree/master/Demo)
We intentionally "keep it simple, stupid" because we are focused on library itself.
If it isn't what you want, feel free to create an awesome one using this library. : )

**Comment by GAMELASTER** [comment]
Okay, thanks! Nice, i will build that! I just want a mkv anime player what will going fast! Just i need to integrate a subtitles ! Thanks
