### ISSUE TITLE
在UWP环境下，全屏化闪退

### ISSUE THREAD

**Issue by wcavell** [amamiya/SYEngine#7]
在启用了AreTransportControlsEnabled 点击全屏化按钮，触发异常。

**Comment by amamiya** [comment]
十分抱歉我现在才看到……
这个项目我已经暂时无限期搁置了，如果现阶段有什么问题，麻烦自己修修了……
还请谅解。
希望以后某天还有重启的可能吧……

**Comment by silverdragon727** [comment]
@wcavell 麻烦提供一下详细情况 (异常信息、截图之类的)
@amamiya 怎么弄得和跟着小姨子跑路了似的……这可是第二个大坑了啊……

**Comment by wcavell** [comment]
看见这个项目更新了，最后这个问题是由于系统自己的问题，目前的10586已修复此问题。
